export const AssetRegistry = {
  Player: {
    WALKER_STAND: "robot1_stand",
    WALKER_HOLD: "robot1_hold",
  },
  Enemy: {
    CRAWLER_STAND: "zombie1_stand",
    CRAWLER_HOLD: "zombie1_hold",
  },
  Terrain: {
    GRASS_01: "tile_01",
    GRASS_02: "tile_02",
    GRASS_03: "tile_03",
    GRASS_04: "tile_04",
    DIRT_05: "tile_05",
    DIRT_06: "tile_06",
    DIRT_07: "tile_07",
    DIRT_08: "tile_08",
    DIRT_09: "tile_09",
  },
  Trees: {
    TREE_131: "tile_131",
    TREE_132: "tile_132",
  },
  Rocks: {
    ROCK_100: "tile_100",
    ROCK_101: "tile_101",
    ROCK_102: "tile_102",
    ROCK_103: "tile_103",
    ROCK_104: "tile_104",
    ROCK_105: "tile_105",
    ROCK_106: "tile_106",
    ROCK_107: "tile_107",
  },
  Effects: {
    CYAN_SPLATTER: "effect_splatter_cyan",
    GREEN_SPLATTER: "effect_splatter_green",
  },
  Placeholder: {
    PLAYER: "char_player",
    SLIME: "enemy_slime",
    WOLF: "enemy_wolf",
    GOBLIN: "enemy_goblin",
    COIN: "loot_coin",
    HEALTH_ORB: "loot_health_orb",
    ATTACK_SWEEP: "effect_attack_sweep",
    NPC: "char_npc",
    ITEM_BAG: "loot_item_bag",
  },

  // Flat legacy mappings for backwards compatibility
  GRASS: "tile_grass",
  TREE: "obstacle_tree",
  ROCK: "obstacle_rock",
  PLAYER: "char_player",
  SLIME: "enemy_slime",
  WOLF: "enemy_wolf",
  GOBLIN: "enemy_goblin",
  COIN: "loot_coin",
  HEALTH_ORB: "loot_health_orb",
  ATTACK_SWEEP: "effect_attack_sweep",
  NPC: "char_npc",
  ITEM_BAG: "loot_item_bag",
};
